# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5908c166a338217f94a28a2ae5dc747e0973eadf418fc485e937875eb92bd2d727b21b7124c5f822df72abd90b4156eea9402e4560f2906ed3ed07562d531dd

test:
  secret_key_base: bd232c5ad7c3ba910ca70318145ccf58f96a2acb272be2641799b007d77c3deea753c397738c4506827c26c46501481673d9ac43952bb3cb753a5cde7634e741

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
